import {
  ABOUT,
  HOME,
  LOGIN,
  PROFILE,
  REGISTER,
  ROOT,
  EDIT,
  EDIT_ALL,
  EDIT_EMAIL,
  EDIT_PASSWORD,
  EDIT_PHONE,
  DELETE_USER
} from "./routePaths";

import {
  API_URL_BASE,
  LOGIN_ENDPOINT,
  REGISTER_ENDPOINT,
  PROFILE_ENDPOINT,
  DELETE_USER_ENDPOINT,
  UPDATE_EMAIL_ENDPOINT,
  UPDATE_ENDPOINT,
  UPDATE_PASSWORD_ENDPOINT,
  UPDATE_PHONE_ENDPOINT,
} from "./api";

export {
  HOME,
  LOGIN,
  REGISTER,
  ROOT,
  API_URL_BASE,
  LOGIN_ENDPOINT,
  REGISTER_ENDPOINT,
  PROFILE,
  ABOUT,
  PROFILE_ENDPOINT,
  EDIT,
  DELETE_USER_ENDPOINT,
  UPDATE_EMAIL_ENDPOINT,
  UPDATE_ENDPOINT,
  UPDATE_PASSWORD_ENDPOINT,
  UPDATE_PHONE_ENDPOINT,
  EDIT_ALL,
  EDIT_EMAIL,
  EDIT_PASSWORD,
  EDIT_PHONE,
  DELETE_USER
};
